[package]
name = "basalt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
bedrock = { git = "http://github.com/basalt-rs/bedrock.git", features = [
    "tokio",
], rev = "8461dc4" }
tokio = { version = "1.43.0", features = ["full"] }
lazy_static = "1.5.0"
tera = "1.20.0"
bollard = "0.18.1"
async-tempfile = "0.6.0"
async-tar = "0.5.0"
tokio-tar = "0.3.1"
indicatif = { version = "0.17.11", features = ["futures"] }
futures = "0.3.31"
console = { version = "0.15.10", features = ["windows-console-colors"] }
